development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: starterKit_development
  pool: 5
  username: root
  password: toor
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ZMan_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ZMan_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
